src/objects/myObj__c.object
<CustomObject>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>myObjs</relationshipLabel>
        <relationshipName>myObjs</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>active__c</fullName>
        <defaultValue>false</defaultValue>
        <label>active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>seasons__c</fullName>
        <label>seasons</label>
        <picklist>
            <picklistValues>
                <fullName>Spring</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Summer</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fall</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>winter</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>serailNo__c</fullName>
        <label>serailNo</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>myObj</label>
    <nameField>
        <label>myObj Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>myObjs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/myObjDetails__c.object
<CustomObject>
    <fields>
        <fullName>myObj__c</fullName>
        <label>myObj</label>
        <referenceTo>myObj__c</referenceTo>
        <relationshipLabel>myObjDetails</relationshipLabel>
        <relationshipName>myObjDetails</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>myObjDetail</label>
    <nameField>
        <label>myObjDetails Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>myObjDetails</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/myObj.cls
public with sharing class myObj
{
    /*private final expSuitepreferences__c preferencesObj;
    String contact_name;
    public expSuitepreferences__c pref;
    public expEmailSeedlist__c[] seed;
    private String delete_id;
    private String fname,lname,email;
    public String mark_delete_id {get;set;}
   */
    public myObj__c myObj;
    public myObjDetails__c[]  mydetalList{get;set;}

    public myObj__c getmyObj()
    {
        try
        {
            myObj = [Select  e.name,active__c,Contact__r.firstName,seasons__c,serailNo__c,(select name from myObjDetails__r) from myObj__c e where
             id =: ApexPages.currentPage().getParameters().get('id') ];
        }
        catch(QueryException e)
        {
            myObj = new myObj__c(Name = 'hhhhh');
        }


         mydetalList = myObj.myObjDetails__r;

    	 myObjDetails__c myDetObj = new myObjDetails__c(name='ahalya',myObj__c=ApexPages.currentPage().getParameters().get('id'));
    	 mydetalList.add(myDetObj);
    	 //myObj.myObjDetails__r.add(myDetObj);


        return myObj;
    }


    public void save()
    {
    	
        myObjDetails__c[]  mydetalList = myObj.myObjDetails__r;
        //System.debug('ALLLOC -->'+myObj.myObjDetails__r[0].name+'  ');
    	update(myObj);
    	update(mydetalList);
    }

     public void clear()
    {
    }

    public void addChild()
    {
    	

    }
}